param(
    [Parameter(Mandatory = $true)]
    [string]$LegacyInstaller,

    [Parameter(Mandatory = $true)]
    [string]$CandidateInstaller,

    [ValidateSet("nsis", "msi")]
    [string]$InstallerType = "nsis",

    [string]$SnapshotPath = ".cp29-rehearsal\baseline-snapshot",

    [string]$AppDataPath = (Join-Path $env:APPDATA "com.englishfocus.desktop")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Install-EnglishFocus {
    param(
        [Parameter(Mandatory = $true)][string]$Installer,
        [Parameter(Mandatory = $true)][string]$Type
    )

    if (-not (Test-Path $Installer)) {
        throw "Installer not found: $Installer"
    }

    if ($Type -eq "msi") {
        $process = Start-Process msiexec.exe -ArgumentList @(
            "/i",
            "`"$Installer`"",
            "/passive",
            "/norestart"
        ) -Wait -PassThru
    }
    else {
        $process = Start-Process $Installer -ArgumentList "/S" -Wait -PassThru
    }

    if ($process.ExitCode -ne 0) {
        throw "Installer failed with exit code $($process.ExitCode): $Installer"
    }
}

Write-Host "PHASE 1 - Install legacy baseline" -ForegroundColor Cyan
Install-EnglishFocus -Installer $LegacyInstaller -Type $InstallerType
Write-Host "Open English Focus and create the CP29 marker state:" -ForegroundColor Yellow
Write-Host "  - user word: cp29marker (or another easy-to-find imported word)" -ForegroundColor Yellow
Write-Host "  - personal note: CP29 UPGRADE MARKER" -ForegroundColor Yellow
Write-Host "  - favorite + tag: cp29-upgrade" -ForegroundColor Yellow
Write-Host "  - non-default theme/interface size" -ForegroundColor Yellow
Write-Host "  - one manual backup generated by the legacy build" -ForegroundColor Yellow
Read-Host "Press Enter only after the legacy marker state and legacy backup exist"

& "$PSScriptRoot\capture-app-data-snapshot.ps1" `
    -OutputPath $SnapshotPath `
    -AppDataPath $AppDataPath `
    -Label "legacy-before-0.9.0-upgrade"

Write-Host "PHASE 2 - Install 0.9.0 release candidate over the legacy build" -ForegroundColor Cyan
Install-EnglishFocus -Installer $CandidateInstaller -Type $InstallerType

& "$PSScriptRoot\compare-app-data-snapshot.ps1" `
    -SnapshotPath $SnapshotPath `
    -AppDataPath $AppDataPath

Write-Host "PHASE 3 - Complete the in-app verification checklist" -ForegroundColor Cyan
Write-Host "  1. App opens without migration or startup error." -ForegroundColor Yellow
Write-Host "  2. CP29 marker word is searchable." -ForegroundColor Yellow
Write-Host "  3. CP29 personal note, favorite and tag remain." -ForegroundColor Yellow
Write-Host "  4. Theme/settings remain." -ForegroundColor Yellow
Write-Host "  5. Legacy backup validates and restores." -ForegroundColor Yellow
Write-Host "  6. Diagnostics reports current schema and consistency PASS." -ForegroundColor Yellow
Write-Host "  7. Installer version reports 0.9.0." -ForegroundColor Yellow
